# .golangci.yml
run:
  timeout: 5m
  go: "1.24"

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats: colored-line-number
