# .golangci.yml
run:
  timeout: 5m
  go: "1.24"

linters:
  disable-all: true
  errcheck:
    ignore: '.*_test\.go|.*/test/.*'
  enable:
    - gofmt
    - gofumpt
    - goimports
    - gci
    - govet
    - staticcheck
    - gosimple

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: q
  gci:
    sections:
      - standard
      - default
      - prefix(q)
    skip-generated: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats: colored-line-number
