run:
  timeout: 2m

linters:
  enable:
    - gofmt
    - staticcheck
    - errcheck

# run only errcheck on non-test files via issue exclusion
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
