brews:
  - name: q
    homepage: "https://github.com/rednafi/q"
    description: "A CLI tool for interacting with AI models"


    directory: Formula

    repository:
      owner: rednafi              # same owner as the code repo
      name:  q                    # same repo name
      branch: main                
      token: "{{ .Env.GITHUB_TOKEN }}"

    commit_author:
      name: GitHub Actions
      email: actions@github.com

    test: |
      system "#{bin}/q", "--help"
    install: |
      bin.install "q"

    dependencies:
      - go
