builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Tag }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
    binary: q
    main: ./cmd/q

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: q
    homepage: https://github.com/rednafi/q
    description: LLM in the Shell™.
    directory: Formula
    repository:
      owner: rednafi
      name: q
      branch: main
      token: '{{ .Env.GITHUB_TOKEN }}'
    commit_author:
      name: GitHub Actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    test: |
      system "#{bin}/q", "--help"
    install: |
      bin.install "q"
    dependencies:
      - name: go
        type: build
nfpms:
  - id: deb
    package_name: q
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.deb'
    formats:
      - deb
    maintainer: "Redowan Delowar <rednafi@gmail.com>"
    description: "LLM in the Shell™."
    homepage: "https://github.com/rednafi/q"
    license: MIT
    priority: extra
    section: utils
    depends:
      - libc6
    conflicts:
      - oldname
