# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Q < Formula
  desc "A CLI tool for interacting with AI models"
  homepage "https://github.com/rednafi/q"
  version "0.1"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/rednafi/q/releases/download/v0.1/q_Darwin_x86_64.tar.gz"
      sha256 "7f8409b8e509b6063393dcde359e04abb64539cb379ec491a723381465dd7fd1"

      def install
        bin.install "q"
      end
    end
    on_arm do
      url "https://github.com/rednafi/q/releases/download/v0.1/q_Darwin_arm64.tar.gz"
      sha256 "9f7ad7ecbed9d396c2bb59f0cece54c21b5160be64b278a9afc01962a43bc17c"

      def install
        bin.install "q"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rednafi/q/releases/download/v0.1/q_Linux_x86_64.tar.gz"
        sha256 "66fd959fb8a5c5ea6287456d7b2d76c3dca284415e1937f73a9dc5561e7186b3"

        def install
          bin.install "q"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rednafi/q/releases/download/v0.1/q_Linux_arm64.tar.gz"
        sha256 "49fdce2bc412abe1a1ee15549cc7b7cab25c0bc9bfc8d2715eca3fd0c168a9ba"

        def install
          bin.install "q"
        end
      end
    end
  end

  test do
    system "#{bin}/q", "--help"
  end
end
