# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Q < Formula
  desc "A CLI tool for interacting with AI models"
  homepage "https://github.com/rednafi/q"
  version "0.1"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/rednafi/q/releases/download/v0.1/q_Darwin_x86_64.tar.gz"
      sha256 "49e61b8f9898d7e604ce5f7e9639e21f1329a2051f27fa9bde3c9f1badd20e8f"

      def install
        bin.install "q"
      end
    end
    on_arm do
      url "https://github.com/rednafi/q/releases/download/v0.1/q_Darwin_arm64.tar.gz"
      sha256 "ef228fe6578b95b80ea1ac2edfe1dd8ef78c799f8fea2938717b072c64faa085"

      def install
        bin.install "q"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rednafi/q/releases/download/v0.1/q_Linux_x86_64.tar.gz"
        sha256 "d26510cadc445932d7621cdd66a7f0426105e6a63ff1a2bb7acf09a403e14253"

        def install
          bin.install "q"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rednafi/q/releases/download/v0.1/q_Linux_arm64.tar.gz"
        sha256 "382a36dd8d55d4c0cd8fdaacd2f5b76736a3a7c32363708497b51f75a525cc6b"

        def install
          bin.install "q"
        end
      end
    end
  end

  test do
    system "#{bin}/q", "--help"
  end
end
