# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Q < Formula
  desc "LLM in the Shell™."
  homepage "https://github.com/rednafi/q"
  version "0.3"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/rednafi/q/releases/download/v0.3/q_0.3_Darwin_x86_64.tar.gz"
      sha256 "d1be31f88d718f447bd7d3bec03d161ddd5d8179317fad0eb7c2e84d064402d7"

      def install
        bin.install "q"
      end
    end
    on_arm do
      url "https://github.com/rednafi/q/releases/download/v0.3/q_0.3_Darwin_arm64.tar.gz"
      sha256 "bf626c2dfeb7c279253e1601c2713a51d84bca656e811586b5b82f3173b7a8a2"

      def install
        bin.install "q"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rednafi/q/releases/download/v0.3/q_0.3_Linux_x86_64.tar.gz"
        sha256 "0f4d096df87b1244fb951c1115c760322d973360fb9d4047904429d118efdc7e"

        def install
          bin.install "q"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rednafi/q/releases/download/v0.3/q_0.3_Linux_arm64.tar.gz"
        sha256 "d284ba9f7b9f218376576f198bc5e97b0bfd235921ced8b24024fe032093fdf3"

        def install
          bin.install "q"
        end
      end
    end
  end

  test do
    system "#{bin}/q", "--help"
  end
end
